services:
  - type: web
    name: global-filter-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'import bot; bot.main()'"
    envVars:
      - key: API_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_IDs
        sync: false
